stages:
  - version
  - codequality

version:
  stage: version
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  tags:
    - docker
  script:
    - export GSG_INITIAL_DEVELOPMENT=false
    - export GSG_RELEASE_BRANCHES=master
    - export GL_TOKEN=$TOKENUSER_IMPERSONATE_KEY
    - export GSG_TAG_PREFIX=""
    - echo "RELEASE_VERSION=$(release next-version)" > release_info
    - cat release_info
    - . release_info
    - if [ -z "$RELEASE_VERSION" ]; then exit 1; fi
    - if [ "$CI_COMMIT_BRANCH" = "master" ]; then release changelog; fi
    - if [ "$CI_COMMIT_BRANCH" = "master" ]; then release commit-and-tag --create-tag-pipeline CHANGELOG.md; else release tag; fi
  artifacts:
    paths:
     - release_info
  only:
    - qa
    - master
  except:
    variables:
      - $CI_COMMIT_TITLE =~ /README/
  allow_failure: false

eslint:
  stage: codequality
  image: node:16-alpine
  tags: # Runner tags
    - docker
  script:
    - npm install eslint eslint-config-airbnb eslint-config-prettier eslint-plugin-import eslint-plugin-prettier eslint-plugin-react
    - node_modules/eslint/bin/eslint.js .
  only:
  - merge_requests
  allow_failure: true
