version: "3"

services:
  api:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: sh -c 'npm install nodemon -g && npm i && nodemon start'
